name: CI

on: 
  push:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: brew cask update
      - run: brew cask install flash-player-debugger
