name: CI

on: 
  push:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: brew update
        continue-on-error: true
      - run: brew cask install flash-player-debugger && echo ::set-output name=status::success
        id: install_flash_player_debugger
        continue-on-error: true
      - name: update_cask_family
        if: steps.install_flash_player_debugger.outputs.status != 'success'
        run: |
          set -ex
          brew install jq vitorgalvao/tiny-scripts/cask-repair
          curl -sSLf `brew cask _stanza url flash-player-debugger` -o flash-player-debugger.dmg
          sudo hdiutil attach flash-player-debugger.dmg
          UPSTREAM_VERSON=`plutil -convert json "/Volumes/Flash Player/Flash Player.app/Contents/Info.plist" -o - | jq -r '.CFBundleVersion'`
          cd `brew --repository homebrew/homebrew-cask`
          git fetch --unshallow || true
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          if ! ./developer/bin/update_cask_family flash "$UPSTREAM_VERSON" ; then
            git remote add andyli "https://andyli:${HOMEBREW_GITHUB_API_TOKEN}@github.com/andyli/homebrew-cask.git"
            git fetch andyli
            for branch in $(git for-each-ref --format='%(refname)' "refs/remotes/andyli/bump-flash-*-${UPSTREAM_VERSON}"); do
              git checkout --track "$branch"
              git rebase origin/master
              git push andyli --force
            done
          fi
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          GIT_AUTHOR_NAME: Andy Li
          GIT_AUTHOR_EMAIL: andy@onthewings.net
          GIT_COMMITTER_NAME: Andy Li
          GIT_COMMITTER_EMAIL: andy@onthewings.net
